; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = arduino_nano_esp32

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
  arduino-libraries/Servo

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_speed = 115200
upload_port = /dev/cu.usbmodem744DBDA0F9342
monitor_speed = 9600
monitor_port = /dev/cu.usbmodem744DBDA0F9342

; Enable optional ESP32 I2C telemetry stream for Feather LoRa bridge:
build_flags = -D DEMO_TEST_SENSOR_DATA=1

lib_deps = 
  SPI
  adafruit/Adafruit SHT31 Library
  adafruit/Adafruit Unified Sensor
  sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
  arduino-libraries/Servo
  adafruit/Adafruit GPS Library
  olikraus/U8g2
  chris--a/Keypad
