; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lora_tx

[env]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200
lib_deps =
	RadioHead

[env:lora_tx]
build_flags =
	-D LORA_ROLE_TX

[env:lora_rx]
build_flags =
	-D LORA_ROLE_RX

[env:adafruit_feather_m0]
build_flags =
	-D LORA_ROLE_TX
